config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'

  get '/ping', to: 'application#ping'

  get 'comment_payer', to: 'pages#comment_payer'
  get 'nouvaute', to: 'pages#nouvaute'
  get 'promotion', to: 'pages#promotion'
  get 'minceur', to: 'pages#minceur'
  get 'bio', to: 'pages#bio'

  get 'hygiene', to: 'hygiene#index'
  get 'fruit', to: 'fruit#index'
  get 'viande', to: 'viande#index'
  get 'boisson', to: 'boisson#index'
  get 'epicerie', to: 'epicerie#index'
  get 'nettoyage', to: 'nettoyage#index'
  get 'laitier', to: 'laitier#index'
  get 'boulangerie', to: 'boulangerie#index'
  get 'animaux', to: 'animaux#index'
  get 'bio', to: 'bio#index'
end

app/models/animaux.rb
class Animaux < ApplicationRecord
end

app/models/bio.rb
class Bio < ApplicationRecord
end

app/models/boisson.rb
class Boisson < ApplicationRecord
end

app/models/boulangerie.rb
class Boulangerie < ApplicationRecord
end

app/models/epicerie.rb
class Epicerie < ApplicationRecord
end

app/models/friut.rb
class Friut < ApplicationRecord
end

app/models/hygiene.rb
class Hygiene < ApplicationRecord
end

app/models/laitier.rb
class Laitier < ApplicationRecord
end

app/models/nettoyage.rb
class Nettoyage < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/viande.rb
class Viande < ApplicationRecord
end

app/helpers/animaux_helper.rb
module AnimauxHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/boisson_helper.rb
module BoissonHelper
end

app/helpers/epicerie_helper.rb
module EpicerieHelper
end

app/helpers/fruit_helper.rb
module FruitHelper
end

app/helpers/hygiene_helper.rb
module HygieneHelper
end

app/helpers/laitier_helper.rb
module LaitierHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/viande_helper.rb
module ViandeHelper
end

app/views/shared/_leader.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'leader', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <header class="headers">
        <div class="logo">
            <span>Header</span>
        </div>
        <div class="search-bar">
            <input type="text" placeholder="Rechercher un produit, par ex. lait">
            <button type="submit">
              <%= image_tag "search.png", alt: "Search" %>
            </button>
        </div>
        <div class="icons">
            <%# <img src="location-icon.png" alt="Location">
            <img src="heart-icon.png" alt="Favorites">
            <img src="cart-icon.png" alt="Cart"> %>
        </div>
    </header>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sidebar Menu</title>
  <%= stylesheet_link_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="sidebar">
  <ul>
    <li>
      <a href="#">Fruits et Légumes</a>
      <ul class="submenu">
        <li><a href="#">Fruits</a></li>
        <li><a href="#">Légumes</a></li>
      </ul>
    </li>
    <li>
      <a href="#">Frais</a>
      <ul class="submenu">
        <li><a href="#">Afficher tous les produits</a></li>
        <li><a href="#">Charcuterie traditionnelle</a></li>
        <li><a href="#">Boucherie traditionnelle</a></li>
        <li><a href="#">Volailles</a></li>
        <li><a href="#">Charcuterie et boucherie libre service</a></li>
        <li><a href="#">Poissons et crustacés</a></li>
        <li><a href="#">Autres</a></li>
      </ul>
    </li>
  </ul>
</div>

</body>
</html>

app/views/shared/_sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar">
        <div class="logo">
          <%= image_tag('logo.png', alt: 'Bazar naka Logo') %>
          <%= link_to 'BAZAR NAKA', root_path %>
        </div>
        <div class="search-bar">
          <input type="text" placeholder="Search">
          <button>Search</button>
        </div>
        <ul class="nav-links">
          <li><%= link_to 'Nouvaute', nouvaute_path %></li>
          <li><%= link_to 'Promotion', promotion_path %></li>
          <li><%= link_to 'Minceur', minceur_path %></li>
          <li><%= link_to 'Bio', bio_path %></li>
        </ul>
        <ul class="nav-links">
          <%= image_tag "shopping-cart_199489.png", alt: "Cadi", class: "cart" %>
          <li><a href="#">Cart</a></li>
        </ul>
      </nav>
    </header>
  </body>
</html>